import Head from "next/head";
import { Hero } from "@/src/components/Hero";
import { NextMeetup } from "@/src/components/Highlight";
import { IconGrid } from "@/src/components/IconGrid/IconGrid";
import { Logo } from "@/src/components/Logo";
import { NavBar } from "@/src/components/NavBar";
import { Place } from "@/src/components/Place";
import { PreviousTalks } from "@/src/components/PreviousTalks";
import { FaMeetup } from "react-icons/fa";
import { getMeetups } from "@/src/services/getMeetups";
import { Event } from "@/src/services/types";
import { getMileStoneByEventId } from "@/src/services/getMileStoneByEventId";
import { GithubIssue } from "@/src/components/GithubIssue";

export async function getStaticProps() {
  const { nextEvent, pastEvents } = await getMeetups();
  const issues = await getMileStoneByEventId(nextEvent.id);

  return {
    props: {
      nextEvent,
      pastEvents,
      issues,
    }, // will be passed to the page component as props
  };
}

interface HomeProps {
  nextEvent: Event;
  pastEvents: Array<Event>;
  issues: Array<any>;
}

export default function Home({ nextEvent, pastEvents, issues }: HomeProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-full overflow-hidden">
        <NavBar />
        <Hero>
          <div className="flex flex-col lg:flex-row items-center">
            <div className="flex-1 text-white mb-4 lg:mb-0">
              <Logo className="h-10 md:h-auto mb-4" />

              <Place venue={nextEvent.venue} />
            </div>

            <div className="flex-auto text-sm flex md:justify-end">
              <IconGrid>
                <NextMeetup time={nextEvent.dateTime} />
              </IconGrid>
            </div>
          </div>

          <section>
            <div className="drop-shadow-lg bg-white rounded-lg p-6 mt-12">
              <div>
                <h2 className="font-bold text-black pb-4 text-lg">
                  {nextEvent.title}
                </h2>
                <a
                  href={nextEvent.eventUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-primary underline text-sm flex flex-row items-center gap-2 -mt-4 mb-4"
                >
                  <FaMeetup className="text-red-500 h-6 w-6" />
                  <span>Voir sur Meetups</span>
                </a>
              </div>

              <div
                dangerouslySetInnerHTML={{ __html: nextEvent.description }}
                className="prose prose-sm prose-slate prose-p:leading-relaxed"
              />
            </div>

            {issues?.map((issue) => (
              <div
                key={issue.id}
                className="drop-shadow-lg bg-white rounded-lg p-6 mt-4"
              >
                <GithubIssue issue={issue} />
              </div>
            ))}
          </section>
        </Hero>

        <div className="bg-gray-50">
          <PreviousTalks talks={pastEvents} />
        </div>
      </main>
    </>
  );
}
